repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/hija/clean-dotenv
    rev: v0.0.7
    hooks:
      - id: clean-dotenv
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [--fix, --show-fixes]
